#pragma once

#include <cmath>

// First-order antiderivative anti-aliasing (ADAA1) in RESIDUAL FORM for the
// suite's memoryless saturation curves (v0.5.0 "Circuit Engines" release,
// brief F1 - binding, not an implementation choice).
//
// Plain (whole-curve) ADAA1 evaluates
//
//   y[n] = (F(x[n]) - F(x[n-1])) / (x[n] - x[n-1])
//
// with F the antiderivative of the curve f (Parker/Zavalishin/Le Bivic,
// "Reducing the Aliasing of Nonlinear Waveshaping Using Continuous-Time
// Convolution", DAFx-16). Its LINEAR-regime response is exactly
// (x[n] + x[n-1])/2 - a half-sample delay convolved with a cos(pi*f/fs)
// lowpass (-11.7 dB @ 20 kHz @ 48 k). Applied whole-curve and in-line that
// would (a) smear a single-sample impulse across two samples, violating the
// suite's parallel-bus sample-alignment invariant (docs/adr/0003,
// tests/NullAndAlignmentTests.cpp), and (b) impose an uncompensated
// sample-rate-dependent HF droop on the direct path.
//
// Residual form therefore decomposes every curve into an exactly-aligned
// linear part plus an ADAA-treated nonlinear residual:
//
//   f(x)   = k*x + r(x),      k = f'(0)  (small-signal gain, incl. drive)
//   y[n]   = k*x[n] + y_r[n]
//   y_r[n] = (R(x[n]) - R(x[n-1])) / (x[n] - x[n-1])   if |x[n]-x[n-1]| > eps
//          = r((x[n] + x[n-1]) / 2)                     otherwise
//
// with R the antiderivative of the residual r = f - k*id, eps = 1e-5.
// ADAA1 is linear in the curve, so ADAA1(f) = ADAA1(k*id) + ADAA1(r) and the
// k*id term aliases in neither rendering: the residual carries ALL
// distortion products and receives the full ADAA treatment, while the
// half-sample smear applies only to distortion products - no HF droop, no
// impulse spreading, no phase-discipline violation (asserted by
// tests/AliasingTests.cpp's linear-path flatness/group-delay cases and the
// unmodified alignment tests).
//
// Parallel-delta rule (binding): where a nonlinear delta is summed against a
// linear path (FetCrush LF-extract delta, ConsoleEq iron term), the delta IS
// the ADAA residual y_r - no midpoint evaluation of any linear leg. Since
// drive -> 0 implies r == 0 structurally, neutral nulls are exact by
// construction.
//
// State per channel per stage: one previous input (double) plus its cached
// antiderivative - reset in reset(), recomputed on parameter change
// (prepareBlock()). Antiderivatives and divided differences are evaluated in
// double: the R(x) expressions subtract nearly-equal quantities at small
// amplitudes and the divided difference amplifies that error by
// 1/(x - x[n-1]); float internals would surface around the test suite's
// -80..-120 dB null bars.
//
// EXEMPTION RULE (binding, brief F1): OptoLeveler's always-on post-colour
// tanh (fixed drive 1.15) is ADAA-EXEMPT and keeps its memoryless per-sample
// evaluation - even the residual's neighbour-sample contribution (~2.8e-5 at
// the alignment tests' operating point) would break the off-impulse
// REQUIRE < 1e-5 bar, while at drive 1.15 the stage is near-linear and its
// alias floor is guarded by tests/AliasingTests.cpp (<= -80 dBFS). The same
// exemption applies to any future always-on near-linear stage on a
// phase-critical bus; a failing guard is a project-owner escalation, never a
// silent ADAA retrofit.
namespace msrr::adaa
{
    inline constexpr double illConditionEpsilon = 1.0e-5;

    // ln(cosh(x)) without overflow: ln cosh x = |x| + log1p(e^(-2|x|)) - ln 2.
    // Exact for all x (never calls cosh on large arguments).
    inline double logCosh (double x) noexcept
    {
        const auto ax = std::abs (x);
        return ax + std::log1p (std::exp (-2.0 * ax)) - 0.69314718055994531;
    }

    // Test-only hook (see tests/AliasingTests.cpp): when true, every
    // residual is evaluated memoryless (no ADAA divided difference), so the
    // aliasing suite can measure the ADAA-on vs ADAA-off spur delta. A
    // runtime flag rather than a compile-time switch because the Tests
    // binary compiles the identical SharedCode sources as the plugin
    // (Pamplejuce pattern - a #define would fork the build). Never touched
    // by product code; costs one predictable branch per sample.
    inline bool& bypassForTests() noexcept
    {
        static bool bypass = false;
        return bypass;
    }

    namespace detail
    {
        // Taylor coefficients a_n of tanh(b + w) about w = 0, generated by
        // the Riccati recursion that follows from T' = 1 - T^2:
        //
        //   a_0 = tanh(b),  a_1 = 1 - a_0^2,
        //   a_{n+1} = -(1 / (n+1)) * sum_{i=0..n} a_i * a_{n-i}   (n >= 1)
        //
        // Both quantities every tanh-family ADAA stage needs are pure
        // series in w = g*x with the constant AND linear terms already
        // removed by construction:
        //
        //   psi(w) = tanh(b + w) - a_0 - a_1*w = sum_{n>=2} a_n w^n
        //   phi(w) = integral_0^w psi          = sum_{n>=2} a_n w^(n+1)/(n+1)
        //
        // so the stage residual is r(x) = scale*psi(g*x) and its
        // antiderivative is R(x) = (scale/g)*phi(g*x).
        //
        // WHY THE SERIES (numerics, not cosmetics): evaluated in closed form
        // at small drive, phi(w) subtracts lnCosh(b) - a quantity of order 1
        // scaled by 1/g - from a result of order w^3. In the ConsoleEq F8
        // iron path at a near-zero Drive setting that is a ~4e2 constant
        // carrying a 6e-14 ulp on top of a ~1e-9 residual; the ADAA divided
        // difference then divides that noise by (x[n] - x[n-1]) and the
        // flux-domain differentiator that follows amplifies what is left
        // toward Nyquist. Measured effect before this treatment: the §6.6
        // "drive -> 0 nulls against the EQ-only path" probe sat at -63 dBFS
        // instead of below -80 dBFS - pure arithmetic noise, no signal. The
        // series has no cancellation at all, so the null is limited by the
        // curve, not by the arithmetic.
        //
        // Used below |w| <= smallArgument; above it the closed form is both
        // well conditioned (the subtracted terms are then small relative to
        // the result) and cheaper.
        struct TanhTaylor
        {
            static constexpr int order = 14;
            static constexpr double smallArgument = 0.1;

            void prepare (double b) noexcept
            {
                a[0] = std::tanh (b);
                a[1] = 1.0 - a[0] * a[0];

                for (int n = 1; n <= order; ++n)
                {
                    double sum = 0.0;

                    for (int i = 0; i <= n; ++i)
                        sum += a[i] * a[n - i];

                    a[n + 1] = -sum / static_cast<double> (n + 1);
                }
            }

            // psi(w), Horner from the top down: w^2 * sum_{m>=0} a_{m+2} w^m.
            double residual (double w) const noexcept
            {
                double p = 0.0;

                for (int n = order + 1; n >= 2; --n)
                    p = p * w + a[n];

                return p * w * w;
            }

            // phi(w) = w^3 * sum_{m>=0} a_{m+2} w^m / (m + 3).
            double antiderivative (double w) const noexcept
            {
                double p = 0.0;

                for (int n = order + 1; n >= 2; --n)
                    p = p * w + a[n] / static_cast<double> (n + 1);

                return p * w * w * w;
            }

            double a[order + 2] {};
        };

        // Shared divided-difference plumbing. Derived curves provide
        // residualValue(x) and residualAntiderivative(x) via the CRTP-ish
        // function-pointer-free pattern below (plain member calls - each
        // curve struct owns its own state and parameters).
        //
        // Double in, double out: callers whose upstream state is already
        // double (the ConsoleEq F8 flux integrator) must not round through
        // float on the way in, or the rounding jitter reappears as the
        // divided difference's numerator noise.
        template <typename Curve>
        inline double residualStepDouble (Curve& c, double xd) noexcept
        {
            double out;

            if (bypassForTests())
            {
                out = c.residualValue (xd);
                c.x1 = xd;
                c.R1 = c.residualAntiderivative (xd);
                return out;
            }

            if (std::abs (xd - c.x1) > illConditionEpsilon)
            {
                const auto R0 = c.residualAntiderivative (xd);
                out = (R0 - c.R1) / (xd - c.x1);
                c.R1 = R0;
            }
            else
            {
                out = c.residualValue (0.5 * (xd + c.x1));
                c.R1 = c.residualAntiderivative (xd);
            }

            c.x1 = xd;
            return out;
        }

        template <typename Curve>
        inline float residualStep (Curve& c, float x) noexcept
        {
            return static_cast<float> (residualStepDouble (c, static_cast<double> (x)));
        }
    }

    // ---------------------------------------------------------------------
    // f(x) = comp * tanh(g*x)   (TapeSaturator curve: TapeSat, SlapDelay
    // tap, ConsoleEq odd term - NOT OptoLeveler colour, see exemption).
    //
    //   k = comp*g
    //   r = comp*(tanh(g*x) - g*x)
    //   R = comp*(lnCosh(g*x)/g - g*x^2/2)
    struct TanhStage
    {
        void reset() noexcept
        {
            x1 = 0.0;
            R1 = 0.0;
        }

        // Call at block rate whenever drive/compensation may have changed -
        // re-caches the previous sample's antiderivative under the NEW
        // curve so the next divided difference stays consistent.
        void prepareBlock (float driveGainLinear, float compensation) noexcept
        {
            g = static_cast<double> (driveGainLinear);
            comp = static_cast<double> (compensation);
            k = static_cast<float> (comp * g);
            series.prepare (0.0);
            R1 = residualAntiderivative (x1);
        }

        float smallSignalGain() const noexcept { return k; }

        // Full in-line stage: y = k*x + y_r.
        float processSample (float x) noexcept
        {
            return k * x + detail::residualStep (*this, x);
        }

        // Residual only (parallel-delta rule).
        float processResidual (float x) noexcept
        {
            return detail::residualStep (*this, x);
        }

        double residualValue (double x) const noexcept
        {
            const auto w = g * x;

            if (std::abs (w) <= detail::TanhTaylor::smallArgument)
                return comp * series.residual (w);

            return comp * (std::tanh (w) - w);
        }

        double residualAntiderivative (double x) const noexcept
        {
            const auto w = g * x;

            if (std::abs (w) <= detail::TanhTaylor::smallArgument)
                return (comp / g) * series.antiderivative (w);

            return comp * (logCosh (w) / g - 0.5 * g * x * x);
        }

        double x1 = 0.0;
        double R1 = 0.0;

    private:
        double g = 1.0;
        double comp = 1.0;
        float k = 1.0f;
        detail::TanhTaylor series;
    };

    // ---------------------------------------------------------------------
    // Asymmetric f(u) = scale * (tanh(g*u + b) - tanh(b))   (ConsoleEq F8
    // iron term with DC premagnetisation, SlapDelay F5 record-side
    // saturator - research-neve-1073.md section 2.4).
    //
    //   k = scale * g * sech^2(b) = scale * g * (1 - tanh^2(b))
    //   r = f - k*u
    //   R = scale * (lnCosh(g*u + b)/g - u*tanh(b)) - k*u^2/2
    struct AsymTanhStage
    {
        void reset() noexcept
        {
            x1 = 0.0;
            R1 = 0.0;
        }

        void prepareBlock (float driveGainLinear, float dcBias, float outputScale) noexcept
        {
            g = static_cast<double> (driveGainLinear);
            b = static_cast<double> (dcBias);
            scale = static_cast<double> (outputScale);
            tanhB = std::tanh (b);
            sechSqB = 1.0 - tanhB * tanhB;
            k = scale * g * sechSqB;
            lnCoshB = logCosh (b);
            series.prepare (b);
            R1 = residualAntiderivative (x1);
        }

        float smallSignalGain() const noexcept { return static_cast<float> (k); }

        float processSample (float x) noexcept
        {
            return static_cast<float> (k) * x + detail::residualStep (*this, x);
        }

        float processResidual (float x) noexcept
        {
            return detail::residualStep (*this, x);
        }

        // Double-precision entry point for callers whose input state is
        // already double (ConsoleEq's F8 flux integrator).
        double processResidual (double u) noexcept
        {
            return detail::residualStepDouble (*this, u);
        }

        // r(u) = scale * psi(g*u); the constant and linear parts of
        // tanh(b + w) are removed analytically by the series (see
        // detail::TanhTaylor), so nothing cancels at small drive.
        double residualValue (double u) const noexcept
        {
            const auto w = g * u;

            if (std::abs (w) <= detail::TanhTaylor::smallArgument)
                return scale * series.residual (w);

            return scale * (std::tanh (w + b) - tanhB) - k * u;
        }

        // R(u) = (scale/g) * phi(g*u). Note the closed-form branch
        // subtracts lnCosh(b): the antiderivative's constant of integration
        // is free, and pinning R(0) = 0 keeps the divided difference's
        // numerator free of an O(1/g) offset.
        double residualAntiderivative (double u) const noexcept
        {
            const auto w = g * u;

            if (std::abs (w) <= detail::TanhTaylor::smallArgument)
                return (scale / g) * series.antiderivative (w);

            return scale * ((logCosh (w + b) - lnCoshB) / g - u * tanhB) - 0.5 * k * u * u;
        }

        double x1 = 0.0;
        double R1 = 0.0;

    private:
        double g = 1.0;
        double b = 0.0;
        double scale = 1.0;
        double tanhB = 0.0;
        double sechSqB = 1.0;
        double lnCoshB = 0.0;
        double k = 1.0;
        detail::TanhTaylor series;
    };

    // ---------------------------------------------------------------------
    // f(x) = x*|x| (class-A asymmetry term): k = 0 - already a pure
    // residual; R = |x|^3 / 3. Kept for suite reuse per the brief (FetCrush
    // no longer calls it after the F3 feedback-FET engine replaced the
    // 0.15*x*|x| colour term with the FET epsilon-term).
    struct XAbsStage
    {
        void reset() noexcept
        {
            x1 = 0.0;
            R1 = 0.0;
        }

        void prepareBlock() noexcept { R1 = residualAntiderivative (x1); }

        float processResidual (float x) noexcept
        {
            return detail::residualStep (*this, x);
        }

        double residualValue (double x) const noexcept { return x * std::abs (x); }

        double residualAntiderivative (double x) const noexcept
        {
            const auto ax = std::abs (x);
            return ax * ax * ax / 3.0;
        }

        double x1 = 0.0;
        double R1 = 0.0;
    };
}
